# --- MAPPO-meltingpot specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"
common_reward: False

buffer_size: 64
batch_size_run: 16
batch_size: 32

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0008
hidden_dim: 128
grad_norm_clip: 2

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: True
standardise_returns: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 10
eps_clip: 0.2
name: "mappo"

#mappocheckpoint_path: "/media/kiyoaki/Ventoy/projects/SD_MARL/results/models/mappo_seed913919370_prisoners_dilemma_in_the_matrix__repeated_2025-03-05_11-20"
#load_step: 30001600

#evaluate: True
#render: True
evaluate: False
render: False

# --- logging options
use_tensorboard: True
save_model: True

t_max: 50000000
save_model_interval: 10000000