# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 256
batch_size_run: 128
batch_size: 128

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0007 # 0.0003
hidden_dim: 128

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.001
use_rnn: True
standardise_returns: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 10
eps_clip: 0.2
name: "mappo"

checkpoint_path: "/media/kiyoaki/Ventoy/projects/SD_MARL/results/models/mappo_seed909905724_pz-mpe-simple-spread-v3_2025-01-21_01-09"
load_step: 20003200

evaluate: True
render: True
#evaluate: False
#render: False

use_tensorboard: True
save_model: True

t_max: 20000000
save_model_interval: 20000000